name: Daily Announcements Update

on:
  schedule:
    # 7:00 AM IST
    - cron: '30 1 * * *'

    # 7:00 PM IST
    - cron: '30 13 * * *'

  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  announcements:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests pyarrow fastparquet

      - name: Run announcements pipeline
        run: |
          python announcement.py

      - name: Run Bulk/Block deals Data
        run: |
          python bulk_block.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull origin dev
          git add data
          git diff --cached --quiet || git commit -m "Auto update data"
          git push origin dev
